{% set name = "dodgy" %}
{% set version = "0.2.1" %}
{% set sha256 = "28323cbfc9352139fdd3d316fa17f325cc0e9ac74438cbba51d70f9b48f86c3a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - dodgy

about:
  home: https://github.com/landscapeio/dodgy
  license: MIT
  license_file: LICENSE
  summary: 'Dodgy: Searches for dodgy looking lines in Python code'

extra:
  recipe-maintainers:
    - jakirkham
