# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ROfEGBQJp2JnaOIgSJlEfFX6lASH5t28Ys6bUsHbVcH+I5jNyqaFPM0aEXKaTP7s7Uvp6UA8ERKIcbR2PnklNvRaRk5v82Y2xEeXexxo8lHqIQBXFgTMS2E4BKC1Zhms0Oy2Lheer8BLmoSYBl1T+nhcVPjV756/YF6yozSLTIdrhSARRt8QFWHglij/rlDEyuqGk3WSfWNEIazEu9lg+qxyxzioM7izUFEu/zcFGUWdn+d03qzqOtLPk9uQKShKgmHiF7BW5XaOHEX0OFxS8r8FqdS4O5mtWeXzWlRwzRzctGgKHkQAj4/gkXcVsjN2h82C93YAwc1dCMHiFG5PNzMxn/MeE/nYRVj56SFr7SjPeDHlVjFZbfgWp41ixD1Od/KDCrPDqrMNUE3tVJVyZs/D+DxZszJQX9bZGAPICgp7eKIaJumQ40RFeUsNuxEE5ob9+TNN/2mPXdwVv6UvF46Enc7Dl1GjUp/motponP/GRSc1IY+FN9bycIAT3JIIt4sHNFWjcFU1UUiEgZE/dPPFcaTNKcuYSlN3tdDyKFravSu5Oh6+sOBqsAhfymLn3lD1N7hO8cGQrorWLvHs8wa2BYhlnjSIljf69vfAzq0axY2R4sGwsE6awNI+luomLIB4/X1s4yxv2B6kjzsmFg3yY15bxE/cOGAfRmEAzUg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
