travis:
  secure:
    BINSTAR_TOKEN: WR914QY6xqmt7aUJtEmhUUnIPrfE3jffoF1MmQbybHM3PeZGd50Y4B6eduWqTSKGO7BvUXift9ZTtPhyx8qyqyE8Rcyw1RAgwKYzckX3AFtdMI5/8S47tIPENcLyoeFaSTX5SVSNcWb1y4LmaPSuQp3lDFz9GE5uS6GwJepIqukBykfV+qutzz4MV4STGXV/+fwSyt/qSM3H3i4d4KI2XWb/8zfPuZnFyw+Lna7bgGlSlCfBKKaVhTFc3XuK6tnxAh7/n8k78soP46q3v0w445M52aVAJqgHZA2ffOBgUHEOj9iQjzslN/JH5RByzquQlwoHHdkSaYPWHE1kqij+KFAnVHO5+0dvRE9tcYyQOFwq1OvyEBhM+HWVBHyXNI3i/djydEb5Woj0yp3DBuf68u0po/vNLnBDpj18BMrgJDPsbdK+8CGGRPgDC5NWo9JJBkEaXjvcrLUuL0T3du7q0SM9GHHD9URNtSRV0eobXAd0GZxvh+yssNp0dwOa6gT2XJ+Wa8wuVyFkqe2mwuZ783bsnrNuGJFkPIwUY8U42kHUFLFKyjjVbtoQOfE23zZvrz4jr3NBm+alJ0FVsst+7GUPOFruz78jlHZuN1jfGHliGsI+BfcRqyWmD5pW3ttZMrt5isgntLNaNnDcn4l++hbQMJ2ZkY5rqv8DiftVhrk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
