travis:
  secure:
    BINSTAR_TOKEN: ROfEGBQJp2JnaOIgSJlEfFX6lASH5t28Ys6bUsHbVcH+I5jNyqaFPM0aEXKaTP7s7Uvp6UA8ERKIcbR2PnklNvRaRk5v82Y2xEeXexxo8lHqIQBXFgTMS2E4BKC1Zhms0Oy2Lheer8BLmoSYBl1T+nhcVPjV756/YF6yozSLTIdrhSARRt8QFWHglij/rlDEyuqGk3WSfWNEIazEu9lg+qxyxzioM7izUFEu/zcFGUWdn+d03qzqOtLPk9uQKShKgmHiF7BW5XaOHEX0OFxS8r8FqdS4O5mtWeXzWlRwzRzctGgKHkQAj4/gkXcVsjN2h82C93YAwc1dCMHiFG5PNzMxn/MeE/nYRVj56SFr7SjPeDHlVjFZbfgWp41ixD1Od/KDCrPDqrMNUE3tVJVyZs/D+DxZszJQX9bZGAPICgp7eKIaJumQ40RFeUsNuxEE5ob9+TNN/2mPXdwVv6UvF46Enc7Dl1GjUp/motponP/GRSc1IY+FN9bycIAT3JIIt4sHNFWjcFU1UUiEgZE/dPPFcaTNKcuYSlN3tdDyKFravSu5Oh6+sOBqsAhfymLn3lD1N7hO8cGQrorWLvHs8wa2BYhlnjSIljf69vfAzq0axY2R4sGwsE6awNI+luomLIB4/X1s4yxv2B6kjzsmFg3yY15bxE/cOGAfRmEAzUg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
