travis:
  secure:
    BINSTAR_TOKEN: Zamu/oDG06bg+U7WIe1aC75zEW+zPNHnvMKzSZNUIQ9YmOTNO6A9QulyIHqVMRrbSYwYKR8JYrs24tQPcXz9nyKj8kU7uzHHRp4+BrZjEB1pe0SkNGTtP3sJcB/HYAPjRqki5Jinje6fe35Zz0NteeL0P3z14+IiN+fKb8FqiknmfiXjZkrysPTTnlxybOT9/76kExWVbzxGX5E9dnZliTQyZ4W3NuYxrYsFUnX7dwNyyZ0cfe5jhnYL1TuRfqYH5zSukstwsKAOFJu2E9+Y3/wsvDlpTNIO/46QXg6mfI7jzF9iOcJPN3Nll3N5CPPlY8Oc9C7eloGvjBFT0sxVcGc2SIxNJckEPQiMeqF5AKfUYqGXaEa7x1yollNwfPY17asPhczhZ21/FRY4xrhj10PDH50EmjUh9B9gBsEjoq2uaQWbO1o2rTRXcu/iFib4aeSgEQq6d2QaDGZOPFpE1XDbWSnL08vzCLVNhZSOHFFW8Ay15y1O5E+RwuQjFuoX3coW1WnKJ5mxUdgwZuFnV+F9NmdjDA9Lst5T/JkoLmeHa4TwHn60GTKkIApbhLGV+z5NGPh13rmHOApYzowCneGPeRkTOPmCrH6QjFolo85frdgjsrm4N/BeV1Q8w6s6ZrnDsEcVVE32KtilBbEHrL/tkRoqQNf7pAtX9cmI1ow=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
