travis:
  secure:
    BINSTAR_TOKEN: DWocTUmJyCWCorIe0SHlJbFB6u+8pxO+J/JU7c/aHg3EwL7BXeoy0YQU/RprJCZ/jRM7fp7gQeSJpUqPzVJsbNu1mjwG3sp1HvHYRb351cfNMTwKrk16QUSfE/q1FRJhy0L47nunMjBjcD9zgX+e+p9nBgrc16AxLUmj0sxt6Uz5jrpmeheu8/iob7WBCXusaqpzVyDYx0n1tcr+eTBIGM2rN+ZZhtDePBHaS2LCVvUrqvhVYfnpeaoaMf0rrtdNIa/bb49eSjfw10g58FiGpX8n0OPE37i8wbwyMxZeMnBuXkt1UiBuCPDt0wWnD2Xv8pDILK2CpnNpkYq2I9dX7yPyXdPRQ+hXVJ0IYOmKpBFzSBczkeP9xQWPxXwUdNYF0NvcHlCqFXlpSUjoTiMoROMa0UHMyJJQZEOUP2dQ1Gwkbe2HhAwc4Z9GGOA/oqFTErmtK0YQ27FS5cWP1TAeRXLEr51sE1fWmUMnZL1zJk3xPfzeZA6b8XZ19ciGm/7MdjsgnSFyXOpAIypDGbluuhJLYcwY4Bpwa+lvg2dy1fHLEPwGMgmKlMFj7IEQe0WSwPmQuMmcKH2hMu38paWMFkjQeEBKIIfyxpgALy55yH0FQmA9t2WSWXgciS7hBQhVTsMymF3DSD5HRtwGe1L2hswKefaJBpb3N/Ryv/foKmo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
